Controllers/HistoryController.cs
using MarkFlixAWSApp.Models;
using MarkFlixAWSApp.Services;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MarkFlixAWSApp.Controllers
{
    public class HistoryController : Controller
    {
        private readonly ITautulliService _tautulliService;

        public HistoryController(ITautulliService tautulliService)
        {
            _tautulliService = tautulliService;
        }
        public async Task<IActionResult> Index()
        {
            var history = await GetAllWatchHistory();

            return View(history);
        }

        public async Task<IActionResult> Media(int ratingKey)
        {
            var users = await GetMediaWatchHistory(ratingKey);

            return View(users);
        }

        public async Task<IEnumerable<Content>> GetAllWatchHistory()
        {
            try
            {
                var history = await _tautulliService.GetAllWatchHistory();

                return history;
            }
            catch (Exception ex)
            {
                Debug.Write(ex);

                return Enumerable.Empty<Content>();
            }
        }

        public async Task<IEnumerable<User>> GetMediaWatchHistory(int ratingKey)
        {
            try
            {
                var history = await _tautulliService.GetMediaWatchHistory(ratingKey);

                return history;
            }
            catch (Exception ex)
            {
                Debug.Write(ex);

                return Enumerable.Empty<User>();
            }
        }
    }
}

Controllers/LibrariesController.cs
using MarkFlixAWSApp.Models;
using MarkFlixAWSApp.Services;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MarkFlixAWSApp.Controllers
{
    public class LibrariesController : Controller
    {
        private readonly ITautulliService _tautulliService;

        public LibrariesController(ITautulliService tautulliService)
        {
            _tautulliService = tautulliService;
        }
        public async Task<IActionResult> Index()
        {
            var libraries = await GetLibraries();

            return View(libraries);
        }

        public async Task<IActionResult> Users(int sectionId)
        {
            var users = await GetLibraryUserStats(sectionId);

            return View(users);
        }


        private async Task<IEnumerable<Library>> GetLibraries()
        {
            try
            {
                var libraries = await _tautulliService.GetLibraries();

                return libraries;
            }
            catch (Exception ex)
            {
                Debug.Write(ex);

                return Enumerable.Empty<Library>();
            }

        }

        private async Task<IEnumerable<User>> GetLibraryUserStats(int sectionId)
        {
            try
            {
                var users = await _tautulliService.GetLibraryUserStats(sectionId);
                return users;
            }
            catch (Exception ex)
            {
                Debug.Write(ex);

                return Enumerable.Empty<User>();
            }

        }
    }
}

Controllers/RecentlyAddedController.cs
using MarkFlixAWSApp.Models;
using MarkFlixAWSApp.Services;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MarkFlixAWSApp.Controllers
{
    public class RecentlyAddedController : Controller
    {
        private readonly ITautulliService _tautulliService;

        public RecentlyAddedController(ITautulliService tautulliService)
        {
            _tautulliService = tautulliService;
        }
        public async Task<IActionResult> Index()
        {
            var recentlyAdded = await GetRecentlyAdded();

            return View(recentlyAdded);
        }

        private async Task<IEnumerable<Content>> GetRecentlyAdded()
        {
            try
            {
                var recentlyAdded = await _tautulliService.GetRecentlyAdded();

                return recentlyAdded;
            }
            catch (Exception ex)
            {
                Debug.Write(ex);

                return Enumerable.Empty<Content>();
            }

        }
    }
}

Controllers/UsersController.cs
using MarkFlixAWSApp.Models;
using MarkFlixAWSApp.Services;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MarkFlixAWSApp.Controllers
{
    public class UsersController : Controller
    {
        private readonly IOverseerrService _overseerrService;
        private readonly ITautulliService _tautulliService;
        private readonly ITheMovieDBService _theMovieDBService;

        public UsersController(
            IOverseerrService overseerrService,
            ITautulliService tautulliService,
            ITheMovieDBService theMovieDBService)
        {
            _overseerrService = overseerrService;
            _tautulliService = tautulliService;
            _theMovieDBService = theMovieDBService;
        }
        public async Task<IActionResult> Index()
        {
            var users = await GetUsers();
            return View(users);
        }

        public async Task<IActionResult> Requests(int? userId)
        {

            var requests = await GetRequests(userId);
            return View(requests);
        }

        public async Task<IActionResult> History(string userName)
        {

            var history = await GetUserWatchHistory(userName);
            return View(history);
        }

        //GET
        private async Task<IEnumerable<User>> GetUsers()
        {
            try
            {
                //var users = await _tautulliService.GetUsers();
                var users = await _overseerrService.GetUsers();

                return users;
            }
            catch (Exception ex)
            {
                Debug.Write(ex);

                return Enumerable.Empty<User>();
            }

        }

        //GET
        public async Task<IEnumerable<Request>> GetRequests(int? userId)
        {
            try
            {
                var requests = await _overseerrService.GetRequests(userId);

                return requests;
            }
            catch (Exception ex)
            {
                Debug.Write(ex);

                return Enumerable.Empty<Request>();
            }
        }

        //GET
        public async Task<IEnumerable<Content>> GetUserWatchHistory(string userName)
        {
            try
            {
                var requests = await _tautulliService.GetUserWatchHistory(userName);

                return requests;
            }
            catch (Exception ex)
            {
                Debug.Write(ex);

                return Enumerable.Empty<Content>();
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MarkFlixWebAPI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MarkFlixWebAPI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/dashboard.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
                <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" asp-area="" asp-controller="Home" asp-action="Index">MarkFlixWebAPI</a>
                <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @*<input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
                <div class="navbar-nav">
                    <div class="nav-item text-nowrap">
                      <a class="nav-link px-3" href="#">Sign out</a>
                    </div>
                </div>*@
        </nav>
    </header>
    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
              <div class="position-sticky pt-3">
                <ul class="nav flex-column">
                  <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                      <span data-feather="home"></span>
                      Dashboard
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link"  asp-area="" asp-controller="Users" asp-action="Index">
                      <span data-feather="users"></span>
                      Users
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="RecentlyAdded" asp-action="Index">
                      <span data-feather="file-plus"></span>
                      Recently Added
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Libraries" asp-action="Index">
                      <span data-feather="book-open"></span>
                      Libraries
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="History" asp-action="Index">
                      <span data-feather="clock"></span>
                      History
                    </a>
                  </li>
                </ul>
              </div>
            </nav>
            <main role="main" class="col-md-9 ms-sm-auto col-lg-10 px-md-4" style="padding-top:65px">
                @RenderBody()
            </main>
        </div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>
    <script src="~/js/dashboard.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>